services:
  app:
    image: app
    #build:
    #  context: .
    #  dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www
      - /var/www/node_modules
      - /var/www/vendor
    networks:
      - karlhill

  nginx:
    image: nginx:alpine 
    platform: linux/arm64
      #build:
      #context: .
      #dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - /var/www/node_modules
      - /var/www/vendor
      - ../data/letsencrypt:/etc/letsencrypt
      - ../data/www:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - karlhill

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../data/letsencrypt:/etc/letsencrypt
      - ../data/www:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/html --quiet; sleep 12h & wait $${!}; done;'"

networks:
  karlhill:
    driver: bridge
