<?php

return [
    'intro' => 'Staff Aerospace Software Engineer with 20+ years of experience building and delivering production software across national security, aerospace, NASA, and enterprise environments. Combines hands-on engineering with technical leadership, leading software delivery, engineering practices, mentoring, and cross-team execution for mission-critical systems.',
    'current' => [
        'label' => 'Current Role',
        'title' => 'Staff Aerospace Software Engineer',
        'company' => 'Jacobs — National Security',
        'location' => 'Chantilly, VA',
        'period' => 'Sept 2025 — Present',
        'summary' => 'Hands-on software development, technical guidance, delivery leadership, mentoring, and engineering guardrails for a ~10-engineer team across ~20 repositories.',
        'scope' => [
            'owned' => 'Day-to-day software delivery, engineering standards, mentoring, and hands-on implementation across about 20 repositories.',
            'influence' => 'Program priorities, vendor and partner-team dependencies, and integration across repositories.',
            'reserved' => 'Staff individual-contributor role; formal personnel decisions remain with management.',
        ],
        'highlights' => [
            'Lead engineering delivery for a ~10-engineer team across ~20 repositories and multiple deployment environments, sequencing work, coordinating dependencies, and driving integration and release readiness.',
            'Develop mission software, shared interfaces, messaging integrations, and service orchestration while providing technical guidance and reviewing implementation across the team.',
            'Establish engineering guardrails through CI/CD, automated testing, security checks, repository standards, dependency management, and release automation.',
            'Lead Agile planning and execution across internal and partner teams, translating mission priorities into sequenced engineering work and resolving cross-team dependencies and blockers.',
            'Onboarded and coached approximately six engineers through code review, technical feedback, development guidance, and reinforcement of engineering standards.',
        ],
        'skills' => [
            'Python',
            'Technical leadership',
            'Distributed systems',
            'Messaging (RabbitMQ/ActiveMQ)',
            'CI/CD',
            'Testing',
            'Release engineering',
            'Agile / Scrum',
            'Mentoring',
            'Cross-team coordination',
        ],
    ],
    'roles' => [
        [
            'title' => 'Lead Software Engineer',
            'company' => 'SSAI / NASA Goddard Space Flight Center',
            'location' => 'Greenbelt, MD',
            'period' => 'Dec 2017 — Sept 2025',
            'summary' => 'Earth science software other people used: flood maps, satellite-data access, and science publishing.',
            'about_highlights' => [0, 1, 2, 5],
            'highlights' => [
                'Led design and development of an AWS-based flood-mapping system, automating processing and distribution of satellite-derived flood products.',
                'Modernized LAADS DAAC web systems, including Find Data search and ordering and near-real-time access, with GitLab CI/CD and Kubernetes delivery.',
                'Modernized NASA Earth Observatory\'s web platform, improving performance, user experience, and search discoverability for an audience of approximately 1.5 million monthly visitors during that work.',
                'Automated a content-registry workflow, reducing manual dataset-registration work by roughly 60% and improving researcher access.',
                'Built a Ceph-based file and metadata platform for virtual directory mapping and discovery of large scientific datasets.',
                'Led Agile software delivery across NASA teams, coordinating priorities, sprint execution, stakeholder needs, and continuous improvement across Earth science projects.',
            ],
            'skills' => [
                'AWS',
                'Flood mapping',
                'Earth science software',
                'GitLab CI/CD',
                'Docker',
                'Kubernetes',
                'Helm',
                'Ceph',
                'High-traffic web',
                'Scientific data systems',
            ],
        ],
        [
            'title' => 'Senior Software Engineer',
            'company' => 'InformedDNA',
            'location' => 'Washington, DC',
            'period' => 'Jan 2016 — Dec 2017',
            'summary' => 'Case-management software and CRM workflows for genetic counseling operations.',
            'highlights' => [
                'Designed and delivered a Laravel case-management platform connecting counseling workflows, documentation, and billing.',
                'Built CRM enhancements for customer lifecycle workflows and reporting, and tightened maintenance and security processes with operations.',
            ],
            'skills' => [
                'Laravel',
                'Case management',
                'CRM',
                'Healthcare software',
                'Security operations',
            ],
        ],
        [
            'title' => 'Senior Software Engineer',
            'company' => 'Ticomix, Inc.',
            'location' => 'Washington, DC',
            'period' => 'Jun 2012 — Mar 2015',
            'summary' => 'CRM implementation and software delivery for client organizations.',
            'highlights' => [
                'Delivered SugarCRM solutions for more than 20 clients, including the Virginia Department of Transportation and Kastle Systems.',
                'Improved backlog management and delivery practices across client projects.',
            ],
            'skills' => [
                'SugarCRM',
                'Enterprise CRM',
                'Delivery management',
            ],
        ],
    ],
    'earlier' => [
        'title' => 'Earlier Engineering Experience',
        'period' => '1997 — 2012',
        'company' => 'Sabre Corporation · Dante Inc. · Visitar Inc. · Verizon Business',
        'highlights' => [
            'Held software engineering and principal-level roles across travel, enterprise CRM, telecommunications, and managed security.',
            'Built Java and SQL Server services for Finium, a multi-tenant managed-security platform, and contributed to shared testing and code-quality practices.',
        ],
        'skills' => [
            'Managed security',
            'Multi-tenant platforms',
            'CRM',
            'Telecommunications',
            'Travel systems',
        ],
        'entries' => [
            [
                'company' => 'Sabre Corporation · Dante Inc. · Visitar Inc. · Verizon Business',
                'meta' => 'Software engineering & principal roles · 1997–2012',
                'detail' => 'Held software engineering and principal-level roles across travel, enterprise CRM, telecommunications, and managed security — including Finium, a multi-tenant managed-security platform.',
            ],
        ],
    ],
];
