<?php

return [
    'intro' => 'Staff aerospace software engineer with 20+ years building and delivering production software across national security, aerospace, NASA, and enterprise environments. Hands-on in the code and responsible for the engineering system around it—leading software delivery, raising engineering standards, mentoring engineers, resolving cross-team technical problems, and turning mission needs into reliable software.',
    'current' => [
        'label' => 'Current Role',
        'title' => 'Staff Aerospace Software Engineer',
        'company' => 'Jacobs — National Security',
        'location' => 'Chantilly, VA',
        'period' => 'Sept 2025 — Present',
        'summary' => 'Hands-on mission software and technical leadership for a ~10-engineer team across ~20 repositories and multiple environments.',
        'scope' => [
            'owned' => 'Day-to-day software delivery, engineering standards, mentoring, and hands-on implementation across about 20 repositories.',
            'influence' => 'Program priorities, vendor and partner-team dependencies, and integration across repositories.',
            'reserved' => 'Staff individual-contributor role; formal personnel decisions remain with management.',
        ],
        'highlights' => [
            'Lead day-to-day engineering and software delivery for a ~10-engineer team across ~20 repositories and multiple environments: priorities, sprint execution, dependencies, and release readiness.',
            'Coordinate engineering work across the team and vendors—working their sprint cadences, creating and assigning tickets, implementing and delegating work, and clearing dependencies.',
            'Establish engineering guardrails in CI/CD, automated testing, code quality, security scanning, repository standards, pull requests, and release controls.',
            'Anticipate technical, integration, and delivery risks; convene the right engineers and stakeholders and drive issues to resolution before they become blockers.',
            'Design, implement, and review mission software and shared systems—including broker-independent messaging adapters and post-processing pipeline work—while guiding technical approach across services.',
            'Onboarded and coached six engineers, reinforcing technical expectations, ownership, and consistent engineering practice.',
        ],
        'skills' => [
            'Python',
            'Technical leadership',
            'Distributed systems',
            'Messaging (RabbitMQ/ActiveMQ)',
            'CI/CD',
            'Testing',
            'Release engineering',
            'Agile / Scrum',
            'Mentoring',
            'Cross-team coordination',
        ],
    ],
    'roles' => [
        [
            'title' => 'Lead Software Engineer',
            'company' => 'SSAI / NASA Goddard Space Flight Center',
            'location' => 'Greenbelt, MD',
            'period' => 'Dec 2017 — Sept 2025',
            'summary' => 'Earth science software other people used: flood maps, satellite-data access, and science publishing.',
            'highlights' => [
                'Led design and development of an AWS-based flood-mapping system, automating processing and distribution of satellite-derived flood products.',
                'Modernized LAADS DAAC web systems, including Find Data search and ordering and near-real-time access, with GitLab CI/CD and Kubernetes delivery.',
                'Modernized NASA Earth Observatory\'s web platform, improving performance, user experience, and search discoverability for an audience of approximately 1.5 million monthly visitors during that work.',
                'Automated a content-registry workflow, reducing manual dataset-registration work by roughly 60% and improving researcher access.',
                'Built a Ceph-based file and metadata platform for virtual directory mapping and discovery of large scientific datasets.',
            ],
            'skills' => [
                'AWS',
                'Flood mapping',
                'Earth science software',
                'GitLab CI/CD',
                'Docker',
                'Kubernetes',
                'Helm',
                'Ceph',
                'High-traffic web',
                'Scientific data systems',
            ],
        ],
        [
            'title' => 'Senior Software Engineer',
            'company' => 'InformedDNA',
            'location' => 'Washington, DC',
            'period' => 'Jan 2016 — Dec 2017',
            'summary' => 'Case-management software and CRM workflows for genetic counseling operations.',
            'highlights' => [
                'Designed and delivered a Laravel case-management platform connecting counseling workflows, documentation, and billing.',
                'Built CRM enhancements for customer lifecycle workflows and reporting, and tightened maintenance and security processes with operations.',
            ],
            'skills' => [
                'Laravel',
                'Case management',
                'CRM',
                'Healthcare software',
                'Security operations',
            ],
        ],
        [
            'title' => 'Senior Software Engineer',
            'company' => 'Ticomix, Inc.',
            'location' => 'Washington, DC',
            'period' => 'Jun 2012 — Mar 2015',
            'summary' => 'CRM implementation and software delivery for client organizations.',
            'highlights' => [
                'Delivered SugarCRM solutions for more than 20 clients, including the Virginia Department of Transportation and Kastle Systems.',
                'Improved backlog management and delivery practices across client projects.',
            ],
            'skills' => [
                'SugarCRM',
                'Enterprise CRM',
                'Delivery management',
            ],
        ],
    ],
    'earlier' => [
        'title' => 'Earlier Engineering Experience',
        'period' => '1997 — 2012',
        'company' => 'Sabre Corporation · Dante Inc. · Visitar Inc. · Verizon Business',
        'highlights' => [
            'Held software engineering and principal-level roles across travel, enterprise CRM, telecommunications, and managed security.',
            'Built Java and SQL Server services for Finium, a multi-tenant managed-security platform, and contributed to shared testing and code-quality practices.',
        ],
        'skills' => [
            'Managed security',
            'Multi-tenant platforms',
            'CRM',
            'Telecommunications',
            'Travel systems',
        ],
        'entries' => [
            [
                'company' => 'Sabre Corporation · Dante Inc. · Visitar Inc. · Verizon Business',
                'meta' => 'Software engineering & principal roles · 1997–2012',
                'detail' => 'Held software engineering and principal-level roles across travel, enterprise CRM, telecommunications, and managed security — including Finium, a multi-tenant managed-security platform.',
            ],
        ],
    ],
];
