<?php

return [
    'intro' => 'Staff Aerospace Software Engineer at Jacobs. The work is Python mission software, technical delivery, and mentoring on a team of about 10. Previously Lead Software Engineer at SSAI supporting NASA Goddard, 2017 to 2025.',
    'current' => [
        'label' => 'Current Role',
        'title' => 'Staff Aerospace Software Engineer',
        'company' => 'Jacobs — National Security',
        'location' => 'Chantilly, VA',
        'period' => 'Sept 2025 — Present',
        'summary' => 'Python services, shared interfaces, CI/CD, and coaching across about 20 repositories. Team of about 10.',
        'scope' => [
            'owned' => 'Python services, shared interfaces, tests, CI, sequencing, and coaching through reviews.',
            'influence' => 'Program priorities, partner-team dependencies, and integration across repositories.',
            'reserved' => 'Staff individual-contributor role; formal personnel decisions remain with management.',
        ],
        'highlights' => [
            'Develop Python-based mission software, shared interfaces, messaging integrations, and service orchestration across multiple deployment environments.',
            'Guide technical delivery for a team of about 10 engineers across approximately 20 repositories; sequence work, coordinate dependencies, and drive integration and release readiness.',
            'Build shared CI/CD, automated testing, security checks, repository standards, dependency management, and release automation.',
            'Onboarded and coached approximately six engineers through code review, technical feedback, and structured development guidance.',
            'Lead Agile planning and execution, working with program stakeholders and partner teams to turn mission priorities into actionable engineering work.',
        ],
        'skills' => [
            'Python',
            'Technical leadership',
            'CI/CD',
            'DevSecOps',
            'Distributed systems',
            'Messaging (RabbitMQ/ActiveMQ)',
            'Release automation',
            'Agile / Scrum',
            'Engineer development',
            'Cross-team coordination',
        ],
    ],
    'roles' => [
        [
            'title' => 'Lead Software Engineer',
            'company' => 'SSAI / NASA Goddard Space Flight Center',
            'location' => 'Greenbelt, MD',
            'period' => 'Dec 2017 — Sept 2025',
            'summary' => 'Earth science software other people used: flood maps, satellite-data access, and science publishing.',
            'highlights' => [
                'Led the design and development of an AWS-based flood-mapping system, automating processing and distribution of satellite-derived flood products.',
                'Modernized LAADS DAAC web systems, including Find Data search and ordering and near-real-time access, with GitLab CI/CD and Kubernetes delivery.',
                'Modernized NASA Earth Observatory\'s web platform, improving performance, user experience, and search discoverability for an audience of approximately 1.5 million monthly visitors during that work.',
                'Automated a content-registry workflow to reduce manual dataset-registration work and improve researcher access.',
                'Built a Ceph-based file and metadata platform for virtual directory mapping and discovery of large scientific datasets.',
            ],
            'skills' => [
                'AWS',
                'Flood mapping',
                'Earth science software',
                'GitLab CI/CD',
                'Docker',
                'Kubernetes',
                'Helm',
                'Ceph',
                'High-traffic web',
                'Scientific data systems',
            ],
        ],
        [
            'title' => 'Senior Software Engineer',
            'company' => 'InformedDNA',
            'location' => 'Washington, DC',
            'period' => 'Jan 2016 — Dec 2017',
            'summary' => 'Case-management software and CRM workflows for genetic counseling operations.',
            'highlights' => [
                'Designed and delivered a Laravel-based case-management platform connecting counseling workflows, documentation, and billing.',
                'Developed CRM enhancements for customer lifecycle workflows and reporting.',
                'Improved platform maintenance and security processes in partnership with operations.',
            ],
            'skills' => [
                'Laravel',
                'Case management',
                'CRM',
                'Healthcare software',
                'Security operations',
            ],
        ],
        [
            'title' => 'Senior Software Engineer',
            'company' => 'Ticomix, Inc.',
            'location' => 'Washington, DC',
            'period' => 'Jun 2012 — Mar 2015',
            'summary' => 'CRM implementation and software delivery for client organizations.',
            'highlights' => [
                'Delivered SugarCRM solutions for more than 20 clients, including the Virginia Department of Transportation and Kastle Systems.',
                'Improved backlog management and delivery practices across client projects.',
            ],
            'skills' => [
                'SugarCRM',
                'Enterprise CRM',
                'Delivery management',
            ],
        ],
    ],
    'earlier' => [
        'title' => 'Earlier Engineering Experience',
        'period' => '1997 — 2012',
        'company' => 'Sabre Corporation · Dante Inc. · Visitar Inc. · Verizon Business',
        'highlights' => [
            'Held software engineering and principal-level roles across travel, enterprise CRM, telecommunications, and managed security.',
            'Built Java and SQL Server services for Finium, a multi-tenant managed-security platform, and contributed to shared testing and code-quality practices.',
        ],
        'skills' => [
            'Managed security',
            'Multi-tenant platforms',
            'CRM',
            'Telecommunications',
            'Travel systems',
        ],
        'entries' => [
            [
                'company' => 'Sabre Corporation · Dante Inc. · Visitar Inc. · Verizon Business',
                'meta' => 'Software engineering & principal roles · 1997–2012',
                'detail' => 'Held software engineering and principal-level roles across travel, enterprise CRM, telecommunications, and managed security — including Finium, a multi-tenant managed-security platform.',
            ],
        ],
    ],
];
