<?php

return [
    'language_colors' => [
        'JavaScript' => '#f1e05a',
        'TypeScript' => '#3178c6',
        'Python' => '#3572A5',
        'PHP' => '#4F5D95',
        'Java' => '#b07219',
        'HTML' => '#e34c26',
        'CSS' => '#563d7c',
        'Shell' => '#89e051',
        'Go' => '#00ADD8',
        'Ruby' => '#701516',
        'Blade' => '#f7523f',
        'Rust' => '#dea584',
    ],
    'fallback_repos' => [
        [
            'name' => 'bb-run',
            'description' => 'Run Bitbucket Pipelines locally from your existing pipeline file before pushing.',
            'problem' => 'Eliminates slow commit-push-fail cycles by executing containerized pipeline steps on local workstations.',
            'url' => 'https://github.com/karlhillx/bb-run',
            'stars' => 1,
            'language' => 'Python',
            'category' => 'CI/CD & Developer Tooling',
            'topics' => [
                'bitbucket-pipelines',
                'devops',
                'cli',
            ],
        ],
        [
            'name' => 'pipeguard',
            'description' => 'Policy-as-code validation and rule enforcement for Bitbucket Pipelines.',
            'problem' => 'Enforces governance, secret safety, and deployment constraints against pipeline YAML definitions before execution.',
            'url' => 'https://github.com/karlhillx/pipeguard',
            'stars' => 0,
            'language' => 'Go',
            'category' => 'Policy-as-Code & Security',
            'topics' => [
                'ci-cd',
                'policy-as-code',
                'governance',
            ],
        ],
        [
            'name' => 'sim-rs',
            'description' => 'High-performance satellite orbit and telemetry simulation engine.',
            'problem' => 'High-throughput orbital mechanics and space vehicle telemetry simulation built in Rust.',
            'url' => 'https://github.com/karlhillx/sim-rs',
            'stars' => 4,
            'language' => 'Rust',
            'category' => 'Simulation & Telemetry',
            'topics' => [
                'simulation',
                'telemetry',
                'aerospace',
            ],
        ],
        [
            'name' => 'driftlens',
            'description' => 'Configuration drift detection and operational risk analysis across environments.',
            'problem' => 'Detects and flags infrastructure, dependency, and configuration variance across operational environments.',
            'url' => 'https://github.com/karlhillx/driftlens',
            'stars' => 2,
            'language' => 'Python',
            'category' => 'Observability & Reliability',
            'topics' => [
                'drift-detection',
                'observability',
                'reliability',
            ],
        ],
        [
            'name' => 'drift-rs',
            'description' => 'High-throughput telemetry and simulation data sink.',
            'problem' => 'Memory-safe streaming data sink for high-volume telemetry ingestion and log capture.',
            'url' => 'https://github.com/karlhillx/drift-rs',
            'stars' => 12,
            'language' => 'Rust',
            'category' => 'Systems & Streaming',
            'topics' => [
                'telemetry',
                'streaming',
                'time-series',
            ],
        ],
        [
            'name' => 'testrisk',
            'description' => 'Rank the highest-value Python test gaps from coverage, AST, and git churn.',
            'problem' => 'Identifies untested code risks by combining AST complexity analysis with git mutation history.',
            'url' => 'https://github.com/karlhillx/testrisk',
            'stars' => 1,
            'language' => 'Python',
            'category' => 'Quality & Testing',
            'topics' => [
                'cli',
                'coverage',
                'testing',
            ],
        ],
    ],
];
