<?php

return [
    [
        'slug' => 'jacobs-mission-software',
        'title' => 'Aerospace mission software',
        'meta' => 'Jacobs · 2025–present',
        'sector' => 'Aerospace & Defense',
        'description' => 'Python mission software spanning shared interfaces, distributed messaging, simulation workflows, and CI/CD across roughly 20 repositories. Technical delivery includes integration across teams and environments, engineering standards, release practices, and coaching for a team of about 10.',
        'image' => '/img/webp/ss-jacobs-ns.webp',
        'image_alt' => 'Jacobs logo',
        'imagePosition' => 'object-center',
        'card_variant' => 'logo',
        'card_image' => '/img/logo-jacobs-mark.png',
        'url' => '/work/jacobs-mission-software',
        'featured' => true,
        'tags' => [
            'Python',
            'AWS',
            'Kubernetes',
            'DevSecOps',
        ],
        'logo' => [
            'path' => '/img/webp/logo-jacobs.webp',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'flood-mapping-system',
        'title' => 'Flood Mapping System',
        'meta' => 'NASA · 2017–2025',
        'sector' => 'NASA Earth Science',
        'description' => 'Python and Docker software for processing and distributing satellite-derived flood maps on AWS. Built to support near-real-time Earth observation products and public access to operational flood data.',
        'image' => '/img/webp/small-flood.webp',
        'imagePosition' => 'object-left-top',
        'url' => 'https://floodmapping.gsfc.nasa.gov/',
        'artifact' => [
            'label' => 'Open the live map',
            'href' => 'https://floodmapping.gsfc.nasa.gov/',
            'line' => 'Public satellite flood maps.',
        ],
        'featured' => true,
        'tags' => [
            'Python',
            'Docker',
            'AWS',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'laads-daac',
        'title' => 'LAADS DAAC',
        'meta' => 'NASA · 2017–2025',
        'sector' => 'NASA Earth Science',
        'description' => 'Software supporting search, ordering, processing, and near-real-time access to NASA MODIS and VIIRS satellite data. Work spanned Perl services, Kubernetes deployments, data workflows, and production systems used by the Earth science community.',
        'image' => '/img/webp/ss-ladsweb.webp',
        'image_alt' => 'NASA LAADS Find Data — product, time, location, files, and review-and-order wizard for MODIS and VIIRS granules.',
        'imagePosition' => 'object-left-top',
        'url' => 'https://ladsweb.modaps.eosdis.nasa.gov/search/',
        'artifact' => [
            'label' => 'Open Find Data',
            'href' => 'https://ladsweb.modaps.eosdis.nasa.gov/search/',
            'line' => 'Live NASA satellite search — Find Data.',
        ],
        'featured' => true,
        'tags' => [
            'Perl',
            'Kubernetes',
            'GitLab CI',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'nasa-earth-observatory',
        'title' => 'NASA Earth Observatory',
        'meta' => 'NASA · 2017–2025',
        'sector' => 'NASA Earth Science',
        'description' => 'Public Earth science publishing platform supporting editorial workflows, imagery, and a global audience.',
        'image' => '/img/webp/ss-earth-observatory.webp',
        'url' => '/work/nasa-earth-observatory',
        'artifact' => [
            'label' => 'Open Earth Observatory',
            'href' => 'https://earthobservatory.nasa.gov/',
            'line' => 'Live Earth Observatory. About 1.5 million monthly visitors during that work.',
        ],
        'featured' => false,
        // Editorial publishing chapter — keep off the main grid; surface as a Goddard supporting chapter.
        'listed' => false,
        'supporting' => true,
        'tags' => [
            'Laravel',
            'MySQL',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'direct-readout-laboratory',
        'title' => 'Direct Readout Laboratory',
        'meta' => 'NASA · 2017–2025',
        'sector' => 'NASA Earth Science',
        'description' => 'Satellite-data ingest, processing, and distribution software supporting direct-readout products and downstream users.',
        'image' => '/img/webp/ss-direct-readout2.webp',
        'url' => 'https://directreadout.sci.gsfc.nasa.gov',
        'artifact' => [
            'label' => 'Open the portal',
            'href' => 'https://directreadout.sci.gsfc.nasa.gov',
            'line' => 'Live direct-readout portal for satellite data products.',
        ],
        'featured' => false,
        // Supporting NASA ingest/ops chapter — not a third flagship card.
        'listed' => false,
        'supporting' => true,
        'tags' => [
            'PHP',
            'Linux',
            'NGINX',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'esscor',
        'title' => 'ESSCOR',
        'meta' => 'NASA · 2017–2025',
        'sector' => 'NASA Earth Science',
        'description' => 'Catalog, search, and data-access software for Earth science holdings.',
        'image' => '/img/webp/ss-esccor.webp',
        'url' => '/work/esscor',
        // Supporting NASA catalog chapter — keep off the main grid.
        'listed' => false,
        'supporting' => true,
        'tags' => [
            'PHP',
            'MySQL',
            'ElasticSearch',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'informeddna-platform',
        'title' => 'InformedDNA Platform',
        'meta' => 'InformedDNA · 2016–2017',
        'sector' => 'Healthcare',
        'description' => 'A Laravel-based case-management platform connecting counseling workflows, documentation, and billing.',
        'image' => '/img/webp/ss-informeddna.webp',
        'url' => 'https://idnaportal.com/',
        // One-year healthcare chapter — real work, off the aerospace trajectory.
        'listed' => false,
        'tags' => [
            'Laravel',
            'MySQL',
            'RESTful APIs',
        ],
        'logo' => [
            'path' => '/img/webp/logo-informeddna.webp',
            'filter' => 'brightness(0) invert(1)',
            'class' => 'h-6',
        ],
    ],
    [
        'slug' => 'finium',
        'title' => 'Finium',
        'meta' => 'Managed security · 1999–2005',
        'sector' => 'Enterprise Security',
        'description' => 'Multi-tenant Java software for provisioning, monitoring, incident management, and security operations. Built for enterprise managed-security environments where reliability and operational visibility were critical.',
        'image' => '/img/webp/ss-mci-verizon.webp',
        'url' => '/work/finium',
        'tags' => [
            'Java',
            'SQL Server',
            'Security',
        ],
        'logo' => [
            'path' => '/img/logo-verizon.svg',
            'filter' => null,
            'class' => 'h-5',
        ],
    ],
];
