<?php

$facts = require __DIR__.'/facts.php';

return [
    [
        'slug' => 'jacobs-mission-software',
        'title' => 'Engineering mission software at scale',
        'card_title' => 'Mission software at scale',
        'meta' => 'Jacobs · 2025–present',
        'sector' => 'Aerospace & Defense',
        'portfolio_group' => 'mission',
        'featured_order' => 1,
        'summary' => [
            'problem' => 'Independent services, inconsistent delivery practices, and integration risk across partner teams.',
            'contribution' => 'Shared CI/CD and DevSecOps gates, portable messaging, integration standards, and hands-on coaching.',
            'impact' => "{$facts['repos_display']} repositories · {$facts['environments_display']} environments · {$facts['onboarded_to']} engineers onboarded",
            'note' => 'Current program scope. Shared ownership; program-specific details are not public.',
        ],
        'description' => 'Hands-on engineering and technical delivery on a simulation program: roughly 20 repositories, three environments, and partner teams. Six engineers onboarded and coached. A portable messaging layer is in use; ownership is shared.',
        'image' => '/img/webp/ss-jacobs-ns.webp',
        'image_alt' => 'Jacobs mark',
        'imagePosition' => 'object-center',
        'card_variant' => 'shot',
        'card_image' => '/img/logo-jacobs-mark.png',
        'url' => '/work/jacobs-mission-software',
        'featured' => true,
        'tags' => [
            'Python',
            'AWS',
            'Kubernetes',
            'DevSecOps',
        ],
        'card_tags' => [
            'Python',
            'AWS',
            'Kubernetes',
        ],
        'logo' => [
            'path' => '/img/webp/logo-jacobs.webp',
            'filter' => null,
            'class' => 'h-8',
            // Wordmark is light artwork — paint it with the canvas ink.
            'ink' => true,
        ],
    ],
    [
        'slug' => 'flood-mapping-system',
        'title' => 'Flood Mapping System',
        'meta' => 'NASA · 2017–2025',
        'sector' => 'NASA Earth Science',
        'portfolio_group' => 'nasa',
        'featured_order' => 2,
        'summary' => [
            'problem' => 'Turn satellite imagery into flood products without a chain of manual processing runs.',
            'contribution' => 'Led Python processing and containerized delivery on AWS, connecting imagery to a public map.',
            'impact' => '90.9% overall accuracy in the published system evaluation',
            'note' => 'Collaborative scientific result, not an individual engineering KPI. Software (Equal), GeoHorizons 2026.',
        ],
        'description' => 'Python and Docker software for processing and distributing satellite-derived flood maps on AWS. Built to support near-real-time Earth observation products. The live map is public; a GeoHorizons paper describes the system.',
        'image' => '/img/webp/small-flood.webp',
        'imagePosition' => 'object-left-top',
        'gallery' => [
            [
                'src' => '/img/webp/small-flood.webp',
                'alt' => 'Public Global Water and Flood Mapping System map',
                'label' => 'Live map',
            ],
            [
                'src' => '/img/webp/ss-geohorizons.webp',
                'alt' => 'GeoHorizons paper describing the flood mapping system',
                'label' => 'GeoHorizons paper',
            ],
        ],
        'url' => '/work/flood-mapping-system',
        'artifact' => [
            'label' => 'Open the live map',
            'href' => 'https://floodmapping.gsfc.nasa.gov/',
            'line' => 'Public satellite flood maps.',
        ],
        'featured' => true,
        'tags' => [
            'Python',
            'Docker',
            'AWS',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'laads-daac',
        'title' => 'LAADS DAAC',
        'card_title' => 'NASA satellite-data search',
        'subtitle' => 'LAADS DAAC / Find Data',
        'meta' => 'NASA · 2017–2025',
        'sector' => 'NASA Earth Science',
        'portfolio_group' => 'nasa',
        'featured_order' => 3,
        'summary' => [
            'problem' => 'Make a complex satellite archive searchable and orderable without replacing its existing interfaces.',
            'contribution' => 'Find Data workflows and incremental delivery modernization with GitLab CI/CD, Helm, and Kubernetes.',
            'impact' => '5-step search-to-order workflow · MODIS and VIIRS access',
            'note' => 'Live public artifact. No query-time or user-growth claim.',
        ],
        'description' => 'Find Data search, ordering, and near-real-time access to NASA MODIS and VIIRS satellite data. Web systems shipped through GitLab CI/CD and Kubernetes alongside existing Perl services.',
        'image' => '/img/webp/ss-ladsweb.webp',
        'image_alt' => 'NASA LAADS Find Data — product, time, location, files, and review-and-order wizard for MODIS and VIIRS granules.',
        'imagePosition' => 'object-left-top',
        'card_parallax' => false,
        'url' => '/work/laads-daac',
        'artifact' => [
            'label' => 'Open Find Data',
            'href' => 'https://ladsweb.modaps.eosdis.nasa.gov/search/',
            'line' => 'Live NASA satellite search — Find Data.',
        ],
        'also' => [
            [
                'label' => 'Broader LAADS site',
                'href' => 'https://ladsweb.modaps.eosdis.nasa.gov/',
            ],
        ],
        'featured' => true,
        'tags' => [
            'Perl',
            'Kubernetes',
            'GitLab CI',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'the-dry-standard',
        'title' => 'The Dry Standard',
        'card_title' => 'The Dry Standard',
        'meta' => 'Independent product · 2026–present',
        'sector' => 'Independent Products',
        'portfolio_group' => 'product',
        'featured_order' => 5,
        'summary' => [
            'problem' => 'Fragmented product information and ambiguous claims make non-alcoholic drinks difficult to compare.',
            'contribution' => 'Designed the domain model, evidence rules, discovery experience, editorial tools, and production application.',
            'impact' => 'One independently owned product, from schema to production',
            'note' => 'Live publication and structured database. No audience or revenue figures claimed.',
        ],
        'description' => 'Independent non-alcoholic drinks publication and structured product database built around transparent classification, production methods, provenance, tasting data, and product discovery.',
        'image' => '/img/webp/ss-dry-standard.webp',
        'image_alt' => 'The Dry Standard — independent reviews and structured non-alcoholic drinks database',
        'imagePosition' => 'object-top',
        'url' => '/work/the-dry-standard',
        'artifact' => [
            'label' => 'Visit The Dry Standard',
            'href' => 'https://drinkdrystandard.com/',
            'line' => 'Independent non-alcoholic drinks publication and structured product database.',
        ],
        'also' => [
            [
                'label' => 'GitHub repository',
                'href' => 'https://github.com/karlhillx/drinkdrystandard.com',
            ],
        ],
        'featured' => true,
        'listed' => true,
        'tags' => [
            'Laravel',
            'SQLite',
            'Vite',
            'Product Engineering',
            'Structured Data',
            'Information Architecture',
            'Search & Discovery',
        ],
        'card_tags' => [
            'Laravel',
            'SQLite',
            'Vite',
        ],
        'logo' => [
            'path' => '/img/logo-dry-standard.svg',
            'filter' => null,
            'class' => 'h-7',
        ],
    ],
    [
        'slug' => 'nasa-earth-observatory',
        'title' => 'NASA Earth Observatory',
        'meta' => 'NASA · 2017–2025',
        'sector' => 'NASA Earth Science',
        'portfolio_group' => 'nasa',
        'summary' => [
            'problem' => 'Support science editors and large imagery on a heavily used public publishing platform.',
            'contribution' => 'Laravel and MySQL platform modernization, reusable editorial workflows, performance, and discoverability.',
            'impact' => '~1.5 million monthly visitors during this work',
            'note' => 'Historical platform scale, not traffic growth attributed to Karl or a current audience figure.',
        ],
        'description' => 'Public Earth science publishing — editorial workflows, imagery, and the live site. Audience scale during that work was about 1.5 million monthly visitors; that is platform size, not a traffic result.',
        'image' => '/img/webp/ss-earth-observatory.webp',
        'url' => '/work/nasa-earth-observatory',
        'artifact' => [
            'label' => 'Open Earth Observatory',
            'href' => 'https://earthobservatory.nasa.gov/',
            'line' => 'Live Earth Observatory. About 1.5 million monthly visitors during that work — platform scale, not a traffic result.',
        ],
        'featured' => false,
        'listed' => false,
        'supporting' => true,
        'tags' => [
            'Laravel',
            'MySQL',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'direct-readout-laboratory',
        'title' => 'Direct Readout Laboratory',
        'meta' => 'NASA · 2017–2025',
        'sector' => 'NASA Earth Science',
        'portfolio_group' => 'nasa',
        'description' => 'Ingest, processing, and distribution software for NASA direct-readout products. The portal is public.',
        'image' => '/img/webp/ss-direct-readout2.webp',
        'image_alt' => 'NASA Direct Readout Laboratory — Real-time Earth observation for societal benefits, with recent software highlights.',
        'imagePosition' => 'object-top',
        'url' => '/work/direct-readout-laboratory',
        'artifact' => [
            'label' => 'Open the portal',
            'href' => 'https://directreadout.sci.gsfc.nasa.gov',
            'line' => 'Live direct-readout portal for satellite data products.',
        ],
        'featured' => false,
        // Supporting NASA ingest/ops chapter — not a third flagship card.
        'listed' => false,
        'supporting' => true,
        'tags' => [
            'PHP',
            'Linux',
            'NGINX',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'esscor',
        'title' => 'ESSCOR',
        'meta' => 'NASA · 2017–2025',
        'sector' => 'NASA Earth Science',
        'portfolio_group' => 'nasa',
        'description' => 'Catalog, search, and access software for Earth science holdings. Shared metadata, discovery, and ordering — no public demo.',
        'image' => '/img/webp/ss-esccor.webp',
        'url' => '/work/esscor',
        // Supporting NASA catalog chapter — keep off the main grid.
        'listed' => false,
        'supporting' => true,
        'tags' => [
            'PHP',
            'MySQL',
            'Elasticsearch',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'developer-tooling',
        'title' => 'Developer tooling & open source',
        'card_title' => 'Engineering the feedback loop',
        'meta' => 'Open source · Independent engineering',
        'sector' => 'Developer Platforms',
        'portfolio_group' => 'tooling',
        'featured' => true,
        'featured_order' => 4,
        'description' => 'A focused body of developer tooling: local pipelines, test-risk analysis, and policy-as-code checks.',
        'summary' => [
            'problem' => 'Slow feedback and hidden operational assumptions make software harder to ship with confidence.',
            'contribution' => 'Built focused tools for local CI, prioritizing test gaps, and pipeline governance.',
            'impact' => 'Inspect the source, tests, and usage documentation',
            'note' => 'Independent projects, not a claim of adoption within Jacobs or NASA.',
        ],
        'image' => '/img/webp/developer-tooling.webp',
        'image_alt' => 'bb-run for local feedback, testrisk for test priorities, and pipeguard for executable policy',
        'url' => '/work/developer-tooling',
        'artifact' => [
            'label' => 'Explore the source',
            'href' => 'https://github.com/karlhillx',
            'line' => 'bb-run, testrisk, and pipeguard: public source and documentation for independent developer tools.',
        ],
        'tags' => ['Python', 'Go', 'CI/CD', 'DevEx'],
        'card_tags' => ['Python', 'Go'],
        'logo' => null,
    ],
    [
        'slug' => 'informeddna-platform',
        'title' => 'InformedDNA Platform',
        'meta' => 'InformedDNA · 2016–2017',
        'sector' => 'Healthcare',
        'portfolio_group' => 'earlier',
        'earlier' => true,
        'description' => 'A Laravel-based case-management platform connecting counseling workflows, documentation, and billing.',
        'image' => '/img/webp/ss-informeddna.webp',
        'url' => '/work/informeddna-platform',
        'artifact' => [
            'label' => 'Open the portal',
            'href' => 'https://idnaportal.com/',
        ],
        // One-year healthcare chapter — real work, off the aerospace trajectory.
        'listed' => false,
        'tags' => [
            'Laravel',
            'MySQL',
            'RESTful APIs',
        ],
        'logo' => [
            'path' => '/img/webp/logo-informeddna.webp',
            'filter' => 'brightness(0) invert(1)',
            'class' => 'h-6',
        ],
    ],
    [
        'slug' => 'finium',
        'title' => 'Finium',
        'meta' => 'Managed security · 1999–2005',
        'sector' => 'Enterprise Security',
        'portfolio_group' => 'earlier',
        'earlier' => true,
        'description' => 'Multi-tenant Java software for provisioning, monitoring, incident management, and security operations. Built for enterprise managed-security environments where reliability and operational visibility were critical.',
        'image' => '/img/webp/ss-mci-verizon.webp',
        'url' => '/work/finium',
        // Earlier managed-security chapter — keep routable, off the flagship grid.
        'listed' => false,
        'tags' => [
            'Java',
            'SQL Server',
            'Security',
        ],
        'logo' => [
            'path' => '/img/logo-verizon.svg',
            'filter' => null,
            'class' => 'h-5',
        ],
    ],
];
