<?php

return [
    [
        'slug' => 'nasa-earth-observatory',
        'title' => 'NASA Earth Observatory',
        'meta' => 'NASA · 2017–2025',
        'description' => 'Flagship science-communication platform serving 1.5M+ monthly visitors with satellite imagery and Earth science data. Led the architectural overhaul of the publishing pipeline — re-platforming editorial workflows for distributed content teams and hardening the delivery layer for accessibility, performance, and search at scale. Set the technical direction that turned ad-hoc story production into a repeatable, self-service system built to evolve for the next decade.',
        'image' => '/img/webp/ss-earth-observatory.webp',
        'url' => 'https://earthobservatory.nasa.gov',
        'featured' => true,
        'tags' => [
            'Laravel',
            'AWS',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'flood-mapping-system',
        'title' => 'Flood Mapping System',
        'meta' => 'NASA · 2017–2025',
        'description' => 'Mission-critical geospatial platform generating near-real-time flood inundation maps during active global disaster events. Architected the fully automated pipeline — from raw satellite sensor ingestion through geospatial product generation, dissemination, and integration with international emergency-management networks — engineered for fault tolerance and reliability when latency is measured in hours, not sprints.',
        'image' => '/img/webp/small-flood.webp',
        'imagePosition' => 'object-left-top',
        'url' => 'https://floodmapping.gsfc.nasa.gov/',
        'featured' => true,
        'tags' => [
            'Python',
            'Docker',
            'AWS',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'direct-readout-laboratory',
        'title' => 'Direct Readout Laboratory',
        'meta' => 'NASA · 2017–2025',
        'description' => 'Real-time scientific data-processing hub ingesting multi-instrument sensor streams from polar-orbiting satellites. Designed the ingestion and reformatting architecture that transforms raw downlinks into Level-0 through Level-2 geophysical products, sustaining 24/7 distribution to operational centers and a global network of registered direct-broadcast ground stations.',
        'image' => '/img/webp/ss-direct-readout2.webp',
        'url' => 'https://directreadout.sci.gsfc.nasa.gov',
        'featured' => true,
        'tags' => [
            'PHP',
            'Linux',
            'NGINX',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'esscor',
        'title' => 'ESSCOR',
        'meta' => 'NASA · 2017–2025',
        'description' => 'Earth science data-discovery platform unifying archival and near-real-time remote-sensing holdings into a single searchable, standards-compliant catalog. Designed granule-level access controls and a governed metadata model that streamlined discovery, ordering, and delivery for researchers across federal agencies and partner institutions.',
        'image' => '/img/webp/ss-esccor.webp',
        'url' => '/work/esscor',
        'tags' => [
            'PHP',
            'MySQL',
            'ElasticSearch',
        ],
        'logo' => [
            'path' => '/img/logo-nasa.svg',
            'filter' => null,
            'class' => 'h-8',
        ],
    ],
    [
        'slug' => 'informeddna-platform',
        'title' => 'InformedDNA Platform',
        'meta' => 'InformedDNA · 2016–2017',
        'description' => 'Clinical-genomics workflow platform orchestrating case management, genetic-counseling routing, and billing reconciliation across distributed care teams. Consolidated fragmented, manual operations into a single governed system — role-based access, end-to-end audit trails, and automated documentation pipelines — cutting per-case operational overhead by $30K annually.',
        'image' => '/img/webp/ss-informeddna.webp',
        'url' => 'https://idnaportal.com/',
        'tags' => [
            'Laravel',
            'MySQL',
            'RESTful APIs',
        ],
        'logo' => [
            'path' => '/img/webp/logo-informeddna.webp',
            'filter' => 'brightness(0) invert(1)',
            'class' => 'h-6',
        ],
    ],
    [
        'slug' => 'finium',
        'title' => 'Finium',
        'meta' => 'Verizon Business · 1999–2005',
        'description' => 'Enterprise managed-security platform running multi-tenant client operations across a national carrier network for a Fortune 500 provider. Owned the services that automated provisioning, monitoring, and incident-response orchestration — scaling operations 10× and directly enabling a $105M acquisition.',
        'image' => '/img/webp/ss-mci-verizon.webp',
        'url' => '/work/finium',
        'tags' => [
            'Java',
            'SQL Server',
            'Security',
        ],
        'logo' => [
            'path' => '/img/logo-verizon.svg',
            'filter' => null,
            'class' => 'h-5',
        ],
    ],
];
