<?php

$doiId = '10.1144/gh2025-7';
$doiUrl = 'https://doi.org/'.$doiId;
$zenodoConcept = '10.5281/zenodo.15881676';
$title = 'A web-based high-resolution global water and flood mapping platform';

$abstractParagraphs = [
    'We present the Global Water and Flood Mapping System (GWFMS), an experimental web-based portal supported by NASA, designed to facilitate access to high-resolution surface water and related products derived from commercial satellite data. The system architecture is modular, enabling integration of additional satellite data sources; its current configuration is optimized for PlanetScope optical imagery, which offers near-daily global land surface coverage at high spatial resolution. This temporal frequency enables the detection and monitoring of ephemeral or small-scale flood events that are typically missed by lower-resolution or less frequently updated datasets.',
    'Products generated by GWFMS are disseminated through an on-demand online service, which can be activated, for example, during emergency scenarios, such as developing flood events, to support rapid response. The current system configuration utilizes the PlanetScope Ortho Analytic 4B Surface Reflectance product from Planet Labs. Surface water is detected using the normalized difference water index, in conjunction with a multi-Otsu thresholding algorithm to delineate water bodies.',
    'Validation of the water detection output against the Global Surface Water dataset demonstrates strong overall accuracy exceeding 90%, with a false positive rate of approximately 3.5%. Despite its effectiveness, the system adopts a conservative detection approach in areas characterized by complex terrain, cloud shadow contamination or high turbidity, which may reduce sensitivity in these regions. Nevertheless, GWFMS significantly enhances the capacity to monitor surface water dynamics globally, offering a valuable complement to existing global water datasets – particularly for disaster response agencies and other stakeholders requiring timely, high-resolution hydrological information.',
];

$authors = [
    [
        'name' => 'Frederick S. Policelli',
        'given' => 'Frederick S.',
        'family' => 'Policelli',
        'url' => 'https://orcid.org/0000-0002-7446-7338',
        'orcid' => '0000-0002-7446-7338',
        'affiliation' => 'NASA Goddard Space Flight Center',
    ],
    [
        'name' => 'Albert J. Kettner',
        'given' => 'Albert J.',
        'family' => 'Kettner',
        'url' => 'https://orcid.org/0000-0002-7191-6521',
        'orcid' => '0000-0002-7191-6521',
        'affiliation' => 'University of Colorado Boulder',
    ],
    [
        'name' => 'Karl M. Hill',
        'given' => 'Karl M.',
        'family' => 'Hill',
        'self' => true,
        'url' => 'https://orcid.org/0009-0002-6847-3368',
        'orcid' => '0009-0002-6847-3368',
        'affiliation' => 'Jacobs',
    ],
    [
        'name' => 'Devon V. Maloney',
        'given' => 'Devon V.',
        'family' => 'Maloney',
        'url' => 'https://orcid.org/0000-0002-6330-2335',
        'orcid' => '0000-0002-6330-2335',
        'affiliation' => 'Federal Emergency Management Agency',
    ],
];

return [
    'slug' => 'global-flood-mapping',
    'path' => '/research/global-flood-mapping',
    'label' => 'Co-author',
    'identity_label' => 'Peer-reviewed research',
    'identity' => 'Co-author, A web-based high-resolution global water and flood mapping platform, GeoHorizons (AGU / Geological Society of London), 2026. Software engineering for a NASA-supported system delivering near-real-time, high-resolution satellite-derived water and flood products worldwide.',
    'credit_label' => 'Author contribution (CRediT)',
    'credit' => 'Software (Equal); Writing – review & editing (Equal)',
    'publication' => 'GeoHorizons',
    'published' => 'Published 7 July 2026',
    'title' => $title,
    'summary' => 'Software (Equal) and Writing – review & editing (Equal) on the Global Water and Flood Mapping System, a NASA-supported platform for near-real-time, high-resolution satellite-derived water and flood products.',
    'intro' => 'The Global Water and Flood Mapping System (GWFMS) is a NASA-supported experimental website that maps surface water and floods from high-resolution commercial satellite imagery. It currently uses near-daily PlanetScope data and can serve products on demand during flood events. The public map is the shipped artifact; this page is the engineering companion to the 2026 GeoHorizons paper.',
    'plain_english' => 'The current configuration uses PlanetScope Ortho Analytic 4B Surface Reflectance. Surface water is detected with the normalized difference water index and a multi-Otsu threshold. The method is more conservative in complex terrain, cloud shadows, and turbid water.',
    'contribution' => 'Led software engineering for the AWS-based processing and delivery platform behind GWFMS, using Python and Docker to generate and deliver satellite-derived flood products. The system replaced a chain of manual runs with a maintained service that could produce high-resolution flood products on demand. The public map is the shipped artifact.',
    'writing' => 'Equal contribution to writing, review, and editing of the published article. Scientific methodology and evaluation were collaborative contributions across the research team.',
    'results' => [
        [
            'value' => '90.9%',
            'label' => 'Overall accuracy',
        ],
        [
            'value' => '87.5%',
            'label' => 'Precision',
        ],
        [
            'value' => '74.1%',
            'label' => 'Recall',
        ],
        [
            'value' => '0.80',
            'label' => 'F1 score',
        ],
        [
            'value' => '0.67',
            'label' => 'Intersection over union',
        ],
        [
            'value' => '3.5%',
            'label' => 'False-positive rate',
        ],
    ],
    'results_note' => 'Aggregated water-map evaluation against the Global Surface Water dataset. False-negative rate is 25.9% — the paper describes a conservative mapping strategy that keeps false alarms low.',
    'keywords' => [
        'Karl Hill',
        'NASA flood mapping',
        'NASA Global Water and Flood Mapping',
        'GWFMS',
        'Global Water and Flood Mapping System',
        'GeoHorizons',
        'satellite-derived flood products',
    ],
    'abstract' => $abstractParagraphs,
    'date_published' => '2026-07-07',
    'date_accepted' => '2026-02-07',
    'volume' => '1',
    'issue' => '1',
    'article_number' => 'gh2025-7',
    'issn' => '2977-4098',
    'eissn' => '2977-4101',
    'language' => 'en',
    'citation' => 'Frederick S. Policelli, Albert J. Kettner, Karl M. Hill, and Devon V. Maloney.',
    'citation_full' => 'Policelli, F.S., Kettner, A.J., Hill, K.M. and Maloney, D.V. 2026. '.$title.'. GeoHorizons, 1(1), gh2025-7, '.$doiUrl,
    'authors' => $authors,
    'journal' => 'GeoHorizons, 1(1), gh2025-7. Geological Society of London / AGU.',
    'publisher' => 'Geological Society of London',
    'publisher_url' => 'https://www.geolsoc.org.uk',
    'license' => 'https://creativecommons.org/licenses/by/4.0/',
    'license_name' => 'CC BY 4.0',
    'doi' => $doiUrl,
    'doi_id' => $doiId,
    'doi_label' => 'Read the paper',
    'publisher_html' => 'https://www.lyellcollection.org/doi/'.$doiId,
    'publisher_pdf' => 'https://www.lyellcollection.org/doi/pdf/'.$doiId,
    'ads' => 'https://ui.adsabs.harvard.edu/abs/'.$doiId,
    'gwfms' => 'https://floodmapping.gsfc.nasa.gov/',
    'zenodo' => 'https://doi.org/'.$zenodoConcept,
    'zenodo_doi' => $zenodoConcept,
    'zenodo_label' => 'Figure datasets on Zenodo',
    'zenodo_description' => 'Datasets used in the figures of “'.$title.'” (GeoHorizons, 2026), deposited on Zenodo.',
    'work_path' => '/work/flood-mapping-system',
    'image' => '/img/ss-geohorizons.png',
    'image_alt' => 'GeoHorizons publication graphic for the global water and flood mapping paper.',
    'figures' => [
        [
            'src' => '/img/webp/small-flood.webp',
            'alt' => 'Public Global Water and Flood Mapping System map showing satellite-derived surface water.',
            'caption' => 'The public GWFMS map. The live service is the shipped artifact for the software described in the paper.',
            'label' => 'Live map',
        ],
        [
            'src' => '/img/ss-geohorizons.png',
            'alt' => 'GeoHorizons publication graphic for the global water and flood mapping paper.',
            'caption' => 'GeoHorizons (Geological Society of London / AGU). Paper figures and the datasets used to produce them are deposited on Zenodo.',
            'label' => 'GeoHorizons',
        ],
    ],
];
